version: '3.9'


services:
  web:
    image: webdevops/php-apache:8.3-alpine     # ← этот образ решает все проблемы с правами
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./www:/app                              # ← именно /app для этого образа
    depends_on:
      - db
  db:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user4_sql_lab          # ← твоя база
      MYSQL_USER: user4_sql_user              # ← твой пользователь
      MYSQL_PASSWORD: 21012000zxc
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql   # ← файл рядом с docker-compose.yml
volumes:
  db_data: